### 404 test
GET {{host}}/mem/non-exist
Accept: */*

### 获取spring MVC locale信息
GET {{host}}/log/locale?lang=en
Accept: */*

### 通过RequestContext获取locale信息
GET {{host}}/log/resolver/locale?lang=zh_TW
Accept: */*

###
# 通过HttpServletRequest获取locale信息
# 遗憾的是，HttpServletRequest.getLocale()方法无法获取当前Locale信息
# 而是根据Accept-Language头设置（如未设置即浏览器默认）的Locale信息
# 所以，Spring MVC context 使用的Locale信息，还是以地址栏参数为准
GET {{host}}/log/request/locale?lang=zh_TW
#Accept-Language: en;q=0.6,zh-CN;q=0.5


### get spitter info by spitterId
GET {{host}}/spitter/{{spitterId}}?lang={{lang}}
Accept: application/json

### error info
GET {{host}}/spitter/{{$randomInt}}?lang={{lang}}
Accept: application/json

### delete spitter by spitterId
DELETE {{host}}/spitter/delete/{{spitterId}}?lang={{lang}}
Accept: application/json

### update spitter info, validate id
POST {{host}}/spitter/update
Content-Type: application/json

{
  "id":4,
  "lastname":"Iguodala",
  "password":"password"
}

### 分页获取spittle， 根据用户spitterId
GET {{host}}/spittle/user/spittles?spitterId={{spitterId}}&currentPage={{currentPage}}&pageSize={{pageSize}}&lang={{lang}}
Accept: */*

### 分页获取spittle， 根据用户spitterId，请求参数放在请求体中的情形:
# public ReqResult<PageDomain<SpittleVO>> getUserSpittlesPage(#RequestBody SpittleDTO spittleDTO) {...}
GET {{host}}/spittle/user/spittles?lang={{lang}}
Accept: */*
Content-Type: application/json

{
  "spitterId": 4,
  "currentPage": 1,
  "pageSize": 1
}

### 分页获取某个时间段的spittle 1
POST {{host}}/spittle/range/spittles?lang={{lang}}
Content-Type: application/json

{
  "leftTime": "2012-06-09 00:00:00",
  "rightTime": "2012-06-09 23:59:59",
  "currentPage":2,
  "pageSize": 1
}

### 分页获取某个时间段的spittle 2
POST {{host}}/spittle/range/spittles?lang={{lang}}
Content-Type: application/json

{
  "spitterId": 4,
  "leftTime": "2012-06-09 00:00:00",
  "rightTime": "2012-06-09 23:59:59",
  "currentPage":2,
  "pageSize": 1
}

### 分页获取某个时间段的spittle 2+
POST {{host}}/spittle/range/spittles?lang={{lang}}
Content-Type: application/json

{
  "spitterId": 4,
  "leftTime": "2012-06-09",
  "rightTime": "2012-06-09 23:59:59",
  "currentPage":2,
  "pageSize": 1
}

### 分页获取某个时间段的spittle 3 测试参数校验异常
POST {{host}}/spittle/range/spittles?lang={{lang}}
Content-Type: application/json

{
  "spitterId": 4,
  "leftTime": "",
  "rightTime": "2012-06-09 23:59:59",
  "currentPage":2,
  "pageSize": 1
}


